### PR TITLE
[README.md] Fix English for ya boi

### PR DESCRIPTION
**Pull request by cszach**
Please check and look for details where your clarification is needed by searching for triple question marks ("`???`") in the current README document.

If everything is okay, just merge. Otherwise, you do the necessary edits.

### CODE REVIEW

**Comment by tachibanayui** [comment]
--- Instruction section ---
- Solution in Visual Studio is just a wrapper of all projects, files and folders. There are only 1 solution in this repos. In fact, when people clone this repo I believe Github for Visual Studio automatically pick up the solution.
- You can fix the references -> "Missing dependencies". Anyway, this will be fix soon :) so this step won't be necessary in the future
- Prebuilt (I think pre-complied is better) *.dll are the files you get when you download the release version of UAD. Again, this will be fix soon like the previous one. In fact they are just the same problem > . <
--- How to use ---
- Version 0.9.0 (v0.9.0) have difference UIs and more feature so I want to cover these new feature in a video tutorial. But I am not working on this at the moment so ....
--- Contributing ---
- Please add my email address: uad.apiservices@gmail.com 
- For contributing just make sure that:  
  - For UIs development: MVVM parttern need to be applied, if you want to make a exception. When pull request, tell why MVVM parttern can't be achived here.
  - For API development: Nothing special, just make sure that don't change the interfaces (currently UADAPI.IQueryAnimeSeries and UADAPI.IAnimeSeriesManager) too much or make change for interfaces in a seprate commit.
--- Coming up in the next release ---
- HLS is short for  HTTP Live Streaming, basically they sepeate the media stream to multiple source then store them in a metadata file (*.m3u8), and its implementation can't be done without change the old downloader code base. To solve this, I will modify the public member: "SegmentedDownloader.DownloadInstance.Add(...)" to accept HLS url
- Please add: "Add support for website that implement CloudFlare"

**Comment by cszach** [comment]
Hey Minh Quan boi,

>     * For contributing just make sure that:
>       
>       * For UIs development: MVVM parttern need to be applied, if you want to make a exception. When pull request, tell why MVVM parttern can't be achived here.
>       * For API development: Nothing special, just make sure that don't change the interfaces (currently UADAPI.IQueryAnimeSeries and UADAPI.IAnimeSeriesManager) too much or make change for interfaces in a seprate commit.

Pfft Im'ma just ignore this, tell me if it's very important.

> HLS is short for HTTP Live Streaming, basically they sepeate the media stream to multiple source then store them in a metadata file (*.m3u8), and its implementation can't be done without change the old downloader code base. To solve this, I will modify the public member: "SegmentedDownloader.DownloadInstance.Add(...)" to accept HLS url

Yeah yeah yeah so basically HLS is a web technology and how dafuq can you "play" it, as quoted from the original README
> Implementing a wat to play HLS inside the app window and download them without change the code base too much

? Can I rephrase that to just "HTTP Live Streaming implementation"?

**Comment by tachibanayui** [comment]
1. I think is important to include the design parttern, I might clost pull request if the design parttern designed too different from mine

2. I want to play it inside the uad window and not downloaded it first. There are example out there in the wpf community such as StackOverflow and MSDN already implement this. Even it not working, [Stream Player](https://www.codeproject.com/Articles/885869/Stream-Player-control) can help playing video directly from source, so the only problem left is to buffer the stream source for it to play

3. I think HLS is enough because people will google it anyway, but it up to you to rephrase that

**Comment by cszach** [comment]
> I think is important to include the design parttern, I might clost pull request if the design parttern designed too different from mine

❓ 

Which design pattern is different from which design pattern? What pull request?

> I want to play it...

Can you just be less vague and tell me, play **WHAT**? You're not telling me to "play HLS" since it's a technology to be implemented and not something to play, are you?

> I think HLS is enough because people will google it anyway, but it up to you to rephrase that

Nah, we can't make assumptions about what people will do. Acronyms should be avoided until their (corresponding) expanded counterparts are mentioned.

**Comment by HoangTheBoss** [comment]
@NOVAglow | Please consider adding `max-width` to screenshots
@quangaming2929 | More freaking typo here #7

**Comment by tachibanayui** [comment]
@NOVAglow  MVVM place behaviour code inside a viewmodel class the UI create a new instance of the viewmodel and assign it ```DataContext``` property, normal implementation place code in code-behind which is the same class with the UI so the data it avaible directly and not through the ```DataContext``` property

**Comment by tachibanayui** [comment]
@HoangTheBoss  #7  is not related to this pull request.

**Comment by tachibanayui** [comment]
```
1. Clone this repository.
2. Open the repository as a solution using Visual Studio.
3. There might be several projects that do not reference correctly to the UI project. To solve this, delete 4. 4. the references and re-add them or re-download them using the Nuget Package Manager.
5. Remove the references to SegmentedDownloader.Core and SegmentedDownloader.Protocol from the 6. project UniversalAnimeDownloader and re-add their pre-compiled DLLs.
7. Remove SegmentedDownloader.Core and SegmentedDownloader.Protocol from the solution.
8. Press F5 or click Start to build Universal Anime Downloader.
```

Please change this to
```
1. Clone this repository.
2. Open the repository as a solution using Visual Studio.
3. Press F5 or click Start to build Universal Anime Downloader.
```

**Comment by cszach** [comment]
Look boi,

I know what MVVM is but I just couldn't interpret what you were trying to talk about because of your flawed written English. I guess I've accumulated enough information to complete this task now. Changes will soon be made. Stand by.

**Comment by cszach** [comment]
Okay Quan. Proofread it. There's only one problem left: The :rainbow: **L I C E N S E** :rainbow:.

Okay, more specifically, I think you should clearly state what rights you grant to your users regarding the software. You don't want them to copy your software and redistribute it all over the Internet without your consent, do you? Well, at least that's an outcome I don't wish to happen.

Oh and the `CONTRIBUTING.md` file too. What the fuck is with it?

>   * For UIs development: MVVM parttern need to be applied, if you want to make a exception. When 
> pull request, tell why MVVM parttern can't be achived here.
>   * For API development: Nothing special, just make sure that don't change the interfaces (currently 
> UADAPI.IQueryAnimeSeries and UADAPI.IAnimeSeriesManager) too much or make change for 
> interfaces in a seprate commit.

That portion of text should be in the `CONTRIBUTING.md`.

**Comment by cszach** [comment]
> @NOVAglow | Please consider adding `max-width` to screenshots

@HoangTheBoss  No.
.
.
.
.
.
.
.
.
.
.
.
Okay look, that does nothing.

**Comment by tachibanayui** [comment]
The ```CONTRIBUTING.md``` made by @HoangTheBoss

**Comment by tachibanayui** [comment]
Also the images, do i need to edit the picture to have uniform size?

**Comment by tachibanayui** [comment]
```
UI development: The model–view–viewmodel (MVVM) is implemented in UAD and you must follow and keep this pattern. If you don't want to use the MVVM pattern, please specifically state why in your pull request.
```
I think most programmers learn WPF know what is MVVM so it not necessary here ( and the full name is long and hard to read too 👁 )

**Comment by cszach** [comment]
> The CONTRIBUTING.md made by @HoangTheBoss

You are in ultimate control of what goes in and out of the UAD repository. Why would you accept an incomplete `CONTRIBUTING.md` into your repository?

> Also the images, do i need to edit the picture to have uniform size?

I do not know how come the images aren't uniform in resolution, but **yes**. Make sure the width of each image is at least 1200 pixels.

> I think most programmers learn WPF know what is MVVM so it not necessary here ( and the full name is long and hard to read too eye )

~Okay, stand by. Getting it fixed.~ It's fixed. :+1:

**Comment by cszach** [comment]
Bro seriously this is getting way too longer than it should be.

**Comment by tachibanayui** [comment]
Okay i think it's good now

**Comment by cszach** [comment]
Thanks brah finally I can forget about it.

By the way, 

1. Do you have a vector graphics (SVG is preferred) version of UAD logo?
2. I am **S U F F E R I N G   F R O M   D E P R E S S I O N**, please tell Hoang that I need him. Thanks.

**Comment by cszach** [comment]
Also,

> **Note**: This section is only for Visual Studio users. If you use another code editor or IDE, please consult the Internet on how to reproduce these steps in your favorite program.

I believe you should give instructions that are more universal, and not just IDE-specific, and prioritize those universal instructions. Can the build process be done using a series of text commands (i.e. in the command line)?

**Pull request merged**
